name: feature pipeline 3


on:
    schedule:
    - cron: '0 * * * *'

    workflow_dispatch:


env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.6.1
  POETRY_URL: https://install.python-poetry.org



jobs:

    feature_pipeline_3:

        runs-on: ubuntu-latest

        steps:

        - id: repo
          name: Repo Checkout
          uses: actions/checkout@v3

        - id: cache
          name: Poetry Caching
          uses: actions/cache@v3
          with:
           path: ~/.local
           key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
    

        - id: python
          name:  Python 3.9 Setup
          uses: actions/setup-python@v3
          with: 
            python-version: ${{ env.PYTHON_VERSION }}
            

        - id: poetry
          name: Poetry Installation
          uses: snok/install-poetry@v1

        - name: Install Dependencies
          run: poetry install
         

        - name: execute python workflow from bash script
          run: poetry run jupyter nbconvert --to notebook --execute notebooks/13_training_pipeline.ipynb

        
        


        

        