
name: hourly taxi demand feature-pipeline

on:
  schedule:
  - cron: '0 * * * *'

  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.6.1
  POETRY_URL: https://install.python-poetry.org

jobs:

  feature_pipeline2:
    runs-on: ubuntu-latest
    steps:
      
    - id: repo
      name: Checkout
      uses: actions/checkout@v3


    - id: cache
      name: Poetry Caching
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
    
    - name: Python Setup 
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - id: poetry 
      name: Poetry Installation
      uses: snok/install-poetry@v1


    - id: dependencies 
      name: Dependencies Installation
      run: poetry install
        
    - name: Run feature generation script
      env: 
        HOPSWORKS_PROJECT_NAME: ${{secrets.HOPSWORKS_PROJECT_NAME }}
        HOPSWORKS_API_KEY: ${{secrets.HOPSWORKS_API_KEY }}

      run: poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb

  
